- hosts: all
  vars_files:
   - /root/2a_var.yml     # create a directory in master /myvariable
  tasks:
    - name: "This task going to Create Directory Name of {{ mydir }} done"
      file:
        path: "{{ mydir }}"
        state: directory

    - name: "This Task going to Copy From {{ myfile }} to {{ mydir }}"
      copy:
       src: "{{ myfile }}"
       dest: "{{ mydir }}"
       owner: sachin
       group: india
       mode: 777
    - name: "This Task is Going to Install packages To Remote Machines {{ mypkg }}"
      yum:
        name: "{{ mypkg }}"
        state: latest

