--- # my first Playbook in dict. yaml format
- hosts: web
  tasks: 
   - copy: 
       src: /etc/passwd
       dest: /tmp/
       owner: sachin
       group: india
       mode:  777


   - file: 
       path: /tmp/ansible
       state: directory

   - yum:
       name: httpd
       state: latest
